### ISSUE TITLE
E-Mail template for changing account type has "+" where spaces should be.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#100]
## Describe the bug
When selecting the "contact support" option on the change account type dialog the template text has "+" where spaces should be on some platforms.

## Steps to Reproduce
1. Go to Settings ("Einstellungen") > My account ("Mein Konto").
2. Tap onto account type ("Account-Type") tile.
3. Tap "contact support" ("Support kontaktieren") button in the dialog.

## Current _broken_ behavior
The text contains "+" where spaces should be.

## Expected behavior
The text should not have these special characters instead of spaces etc.

## Tested device
This does NOT happen with the web app when having gmail inside the browser as the default mail handler.

## Additional context
`UrlLauncherExtended` seems to encode the template text as an URL which causes spaces to be changed to "+".

Original issue: https://gitlab.com/codingbrain/sharezone/sharezone-app/-/issues/1404

**Comment by Jonas-Sander** [comment]
@nilsreichardt Can you add a Screenshot and write on which devices this happens?

**Comment by nilsreichardt** [comment]
![image](https://user-images.githubusercontent.com/24459435/151932454-2cbf3c39-afd4-4230-b158-5a1e105ca5ea.jpeg)

Tested with iPhone

**Comment by ImGxrke** [comment]
Issue can be closed due to #1349 allowing users to change their account type themselves.

**Comment by nilsreichardt** [comment]
That's correct, thanks!
