### ISSUE TITLE
Tab-focus skips "Sign in with Apple" button

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#101]
## Describe the bug
When using tab to change the focus of the active element on the login page the "Sign in with Apple" is skipped.

## Steps to Reproduce
1. Open Sign-In page 
2. Press "TAB" key several times

## Current _broken_ behavior
The tab focus skips the "Sign in with Apple" button.

## Expected behavior
The tab focus should focus the "Sign in with Apple" button after focusing the blue login button.

## Screenshots, videos or logs
https://user-images.githubusercontent.com/29028262/151876611-b538b63b-0866-411e-b4e9-6a40c99db465.mp4

## Tested device
 - Device: PC / MacBook
 - OS: Windows 10 / macOS Big Sur
 - App version: 1.6.2 (316) (Web) / 1.5.81 (taken from AppStore, see #98)

## Additional context
Original issue: https://gitlab.com/codingbrain/sharezone/sharezone-app/-/issues/1396

**Comment by nilsreichardt** [comment]
@Jonas-Sander Why does have this ticket the label `feature: file-sharing`?

**Comment by Jonas-Sander** [comment]
Don't know, good catch! 👍

**Comment by nilsreichardt** [comment]
Fixed with #724
