### ISSUE TITLE
[Android] If Apple Sign-In is aborted a way too large error message appears in a SnackBar.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#109]
## Describe the bug
If Apple Sign-In is aborted a way too large error message with StackTrace appears in a SnackBar.

## Steps to Reproduce
0. Log out if logged in
1. Open Sharezone on an Android device
2. Tap on "Sign-In with Apple"
3. Close the new window (webview) via the "X" icon in the top left corner

## Current _broken_ behavior
An error message with a way too large stack trace is shown.

## Expected behavior
An error message without stack trace should be shown.

## Screenshots, videos or logs
https://user-images.githubusercontent.com/29028262/152432494-079c86a0-c6ba-43ce-87e7-2d32519409b9.mp4

## Tested device
 - Device: Pixel 4a
 - OS: Android 12
 - App version: 1.6.1 (315)

## Additional context
Original Issue: https://gitlab.com/codingbrain/sharezone/sharezone-app/-/issues/1355

**Comment by Jonas-Sander** [comment]
We should see if it is actually correct that the StackTrace is included inside the `PlatformException` as I don't think it is for the other Firebase errors (even the same error on another platform).

**Comment by nilsreichardt** [comment]
Fixed with #776
