### ISSUE TITLE
Add quick options to choose target date when creating a homework.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#1096]
When creating a homework there should be options to automatically choose the next (or second next, 3rd next) lesson where the homework is due, without needing to open the date picker and trying to calculate when the homework is due.  

![grafik](https://github.com/SharezoneApp/sharezone-app/assets/29028262/d4e25338-00e7-4b51-b77d-e44c472a6ff2)

Example (rough prototype):  

https://github.com/SharezoneApp/sharezone-app/assets/29028262/da937fa6-f827-4ac7-ae39-aa6ba6e1f5a1

Things to consider:  
* When choosing the course our current behavior is to pick the next lesson as the due date automatically. This means that the "next lesson" chip should be selected automatically in this case.
* Make chips not selectable if no course is chosen yet
* How should errors be handled when calculating the date for the currently selected chip? -> Display a error text (try again or select a date via date picker or contact the support) and unselect the selected chip (so that the user can tap it to try again)?
Loading behavior
* Is there a special loading behavior? E.g. if a user would press a chip and selects a specific date via the date picker afterwards, before the due date is calculated then the manually picked date should take precedence and should not be replaced with the calculated date. Although the way we the app currently works, such a long loading time should never happen, since the holidays are cached. Not sure if we should rely on this behavior or should implement "proper" loading handling. Maybe there is a longer load time if a user picks a very far lesson in the future?
  * If the date is still loading the homework can't be saved
* Should we automatically select the corresponding chip if a user chooses a date where a lesson is manually? (E.g. he chooses the second next lesson date in the future manually via the date picker)

## Simple Implementation
* Make custom lesson due chips non-deletable (no X) and don't remember them.   
* Make the "next lesson" selected automatically when the date is calculated after choosing a course, but don't bother selecting a the corresponding chip if a manual chosen date aligns with e.g. the second next lesson.  
(Maybe don't even bother implementing the loading behavior here, as it currently should always load quickly (I think))

## Advanced implementation
* Add the option to add a custom "x-next lesson" chip permanently (will keep appearing when adding a homework the next time)
* If a date is selected that corresponds to a visible chip then this chip should be selected
* If not implemented, add better loading behavior
**Not sure, probably not:**
* Make chips be totally customizable (be able to remove e.g. the default chips), change ordering?
* Chips for "tomorrow", "day after tomorrow"?

## Further ideas for the future
* Don't save only the date but "x-next lesson" with the homework. 
  * Canceled lessons will also automatically be ignored when calculating the date chosen by the chip when creating the homework.
  * If a lesson is canceled/not taking place after a homework is already created then the homework due date for that lesson will automatically change to the next lesson afterwards.
  * If the timetable is changed then the dates automatically adapt or the user is asked to choose the new date for the homeworks when after making the timetable change.

Original GitLab issue: https://gitlab.com/codingbrain/sharezone/sharezone-app/-/issues/531

**Comment by nilsreichardt** [comment]
@Jonas-Sander I think this can be closed, right?
