### ISSUE TITLE
Clicking "Save" on a homework multiple times will create duplicates.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#1117]
## Describe the bug
Clicking on "Speichern" in the add homework dialog will create the homework multiple times.

## Steps to reproduce the bug
1. Go to homework page
2. Click "+" button
3. Add titel, course and due date
4. Add a large attachment to the homework (this will prevent the dialog from closing right away, so one can press "Speichern multiple times more easily)
5. Click "Speichern" multiple times

## Current _broken_ behavior
The homework will be created several times

## Expected behavior
The homework should be saved only once. The "Speichern" button should probably be disabled after pressing.

## Screenshots, videos or logs

[](https://github.com/SharezoneApp/sharezone-app/assets/29028262/b9f7916f-06fd-4884-9ba6-61b0fb8cc2bf)

## Tested device
- App version: 1.7.9

**Comment by nilsreichardt** [comment]
Closed with https://github.com/SharezoneApp/sharezone-app/pull/1699
