### ISSUE TITLE
Add premium support to notification with "contact support"?

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#1157]
https://github.com/SharezoneApp/sharezone-app/blob/bbd4a1a68bd465f2bc70a14b53763c7d2029c6e2/app/lib/notifications/action_requests/show_notification_dialog.dart#L116-L138

Should this also change depending on if the user has plus?

Related to #962

**Comment by Jonas-Sander** [comment]
@nilsreichardt

**Comment by nilsreichardt** [comment]
I in the long term yes, but I think it's that urgent and also we haven't really this feature yet.

**Comment by nilsreichardt** [comment]
What about just pushing to the Support page?

**Comment by Jonas-Sander** [comment]
> What about just pushing to the Support page?

Yeah, sounds good

**Comment by nilsreichardt** [comment]
> What about just pushing to the Support page?

Ah, this doesn't make sense because it's about to have the message inside the email:

> body: 'Liebes Sharezone-Team,\n\nihr habt folgende Nachricht geschrieben:\n${actionRequest.title}; ${actionRequest.body}\n\nMein Anliegen:\n_',

I think it's too overkill to add the plus support here. I would just leave it like this.
