### ISSUE TITLE
[Feature Request] Upgrade to Material Design 3 / M3

### ISSUE THREAD

**Issue by Lauritz-Tieste** [SharezoneApp/sharezone-app#1159]
To further improve the look of the Sharezone app, an upgrade to Material Design 3 / M3 and dynamic color would be nice.

[https://m3.material.io/](https://m3.material.io/)

**Comment by deepraj02** [comment]
what changes are you expecting??

**Comment by Lauritz-Tieste** [comment]
Like upgraded widgets and dynamic color

**Comment by nilsreichardt** [comment]
It's a bit more work and requires a few design changes. I think this ticket needs to be implemented by the Sharezone team.
