### ISSUE TITLE
Ignore GeneratedPluginRegistrant.swift in license check

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#120]
![Screenshot_20220204-145926.png](https://user-images.githubusercontent.com/29028262/152541372-498439ed-55ae-4042-82a4-b5f419fcc0e6.png)

We should probably whitelist this file.

_Originally posted by @Jonas-Sander in https://github.com/SharezoneApp/sharezone-app/pull/118#issuecomment-1030010288_

**Comment by nilsreichardt** [comment]
Fixed in #163
