### ISSUE TITLE
"In 3./4... Stunden" will not be removed when changing the "In X Stunden"

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#1271]
https://github.com/SharezoneApp/sharezone-app/assets/24459435/7155fb45-f385-4747-a17b-705c987a00f0

**Comment by nilsreichardt** [comment]
cc: @Jonas-Sander

**Comment by Jonas-Sander** [comment]
Well yes that's how I programmed it to be. I thought that this was the easiest to conceptualize. We can change it though of course. What would you prefer?

**Comment by Jonas-Sander** [comment]
Although I think that creating two chips is very unlikely already and more than that will probably never happen except on purpose.

**Comment by nilsreichardt** [comment]
> Although I think that creating two chips is very unlikely already and more than that will probably never happen except on purpose.

Yes, we can keep it like this 👍
