### ISSUE TITLE
When selecting "In 2 Stunden" a "2.-nächste Stunde" chip is created

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#1272]
![image](https://github.com/SharezoneApp/sharezone-app/assets/24459435/0be07651-817f-4855-886b-5582cb0d6657)

Because we have a "Nächste Stunde" and "Übernächste Stunde" button, I would expect that the '2.-nächste Stunde' is displayed.

**Comment by Jonas-Sander** [comment]
Huh, nice catch. I was sure that this was working... :(
