### ISSUE TITLE
"Abgabeuhrzeit" submission time in homework dialog has very small text size

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#1275]
![grafik](https://github.com/SharezoneApp/sharezone-app/assets/29028262/9a1fb8e8-7c3e-4b21-9415-580023521e20)

**Comment by gantanikhilraj** [comment]
Hello @Jonas-Sander , I would like to work on this issue, assign this to me.

**Comment by nilsreichardt** [comment]
Implemented with #1287
