### ISSUE TITLE
A collection of enhancment ideas

### ISSUE THREAD

**Issue by DAMcraft** [SharezoneApp/sharezone-app#129]
- Entfallende / Vertretende Stunden eintragen können

- REST API

- In Siri-Shortcts ("Kurzbefehle") integration

- die Sharezone-Kursordner in die "Dokumente/Dateien" app integrieren (als speicherort)

- Widgets

- Beim eintragen der Hausaufgaben sollte automatisch der momentane Kurs ausgewählt werden

**Comment by nilsreichardt** [comment]
Hi @DAMcraft,

I created for every idea a feature request ticket. Therefore, we are able to better track this idea better.

* Entfallende / Vertretende Stunden eintragen können: #279 
* REST API: #275 
* In Siri-Shortcts ("Kurzbefehle") integration #280 
* Widgets: #278 
* Beim eintragen der Hausaufgaben sollte automatisch der momentane Kurs ausgewählt werden: #92

What exactly do you mean with "die Sharezone-Kursordner in die "Dokumente/Dateien" app integrieren (als speicherort)"?

**Comment by DAMcraft** [comment]
> What exactly do you mean with "die Sharezone-Kursordner in die "Dokumente/Dateien" app integrieren (als speicherort)

iOS's pre-installed file browser has the ability to add a folder from an external app (useful for FTP and iServ for example)

The idea is to basically being able to access Sharezone files in the pre installed file manager

**Comment by nilsreichardt** [comment]
Ah, ok. Thanks!

I added a feature request for this: #282
