### ISSUE TITLE
Switch buttons are not aligned on the homework dialog page

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#1295]
The homework buttons are not in the vertical position:

![image](https://github.com/SharezoneApp/sharezone-app/assets/24459435/3d58b5b6-7c11-4792-8ad6-52a1c5ee5073)

**Comment by smit-sk** [comment]
Can you explain more about this issue?

**Comment by Amitkumarkoli** [comment]
can u pls explain it more clearly , I am beginner .

**Comment by nilsreichardt** [comment]
<img width="326" alt="image" src="https://github.com/SharezoneApp/sharezone-app/assets/24459435/b22eb08d-dc6e-4775-b45a-7edae719a186">

You can see in this image that the last switch doesn't start at the same position as the other switches do.

**Comment by smit-sk** [comment]
Can I get the root directory path to run this app on my device ?

**Comment by EvilMonkey09** [comment]
@smit-sk You can look in the Contributing.md. There is everything you need.
