### ISSUE TITLE
Former submission homeworks have the wrong subtitle in the dashboard view

### ISSUE THREAD

**Issue by EvilMonkey09** [SharezoneApp/sharezone-app#1306]
Once "Mit Abgabe" is activated, the due to time is set to 23:59 or something else. When the "Mit Abgabe" is now deactivated again, the due to time is still 23:59. This causes the problem, that the due to date is displayed in the dashboard instead of "bis Morgen"

Example:
![Screenshot_20240221_135445_Sharezone.jpg](https://github.com/SharezoneApp/sharezone-app/assets/119407757/b161437d-40ad-4f50-bd58-00689892e194)

**Comment by Jonas-Sander** [comment]
Good catch! Thanks 👍
