### ISSUE TITLE
AppStore buttons in `README.md` are in German

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#141]
The whole `README.md` is in English. Therefore, it's a bit confusing that the AppStore buttons for iOS and macOS are in German.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/24459435/162467319-346f67da-8a52-4f59-ac6d-32c31c45c644.png">

**Comment by sublime247** [comment]
have you been able to solve the issue

**Comment by nilsreichardt** [comment]
@sublime247 I created a PR for this :) https://github.com/SharezoneApp/sharezone-app/pull/259
