### ISSUE TITLE
Use a single-source-of-truth for the flutter version that is used by developers and the CI/CD system.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#144]
Currently we don't have a single source of truth of what version we use to develop and build Sharezone.  
For the CI/CD we define the version inside our action `.yaml` files manually.  
For local development we just have to upgrade/downgrade manually (using the version of the CI system most likely).  

This means there is a risk that:
* we accidentally use the wrong version locally
* forget to upgrade the flutter CI/CD version after upgrading it locally

### Proposed solution

* Use `fvm` (Flutter Version Manager) to access flutter and develop sharezone
* Read the flutter version for the CI/CD system from the configuration file as seen [here (flutter-fvm-config-action)](https://github.com/kuhnroyal/flutter-fvm-config-action)

**Comment by nilsreichardt** [comment]
LGTM

The use of `flutter-fvm-config-action` is also very clever. Hadn't this in my mind that it's much cleaner to do this with an extra action. At first, I wanted to this with a shell script but an action is the better solution 👍  

I can also implement this 👍
