### ISSUE TITLE
iCal export dosn't work

### ISSUE THREAD

**Issue by deep2web** [SharezoneApp/sharezone-app#1561]
## Describe the bug

The site for the iCal export shows the following error

> Es ist ein Fehler aufgetreten!
> [cloud_firestore/permission-denied] Missing or insufficient permissions.

## Steps to reproduce the bug

1. Go to 'Einstellungen'
2. Go to 'Stundenplan'
3. Click on 'Stundenplan exportieren (iCal)'

## Current _broken_ behavior
The iCal export page displays the following error

> Es ist ein Fehler aufgetreten!
> [cloud_firestore/permission-denied] Missing or insufficient permissions.

## Expected behavior

The link for the iCal calendar should be displayed

## Screenshots, videos or logs

![Bildschirmfoto vom 2024-04-25 23-03-48](https://github.com/SharezoneApp/sharezone-app/assets/88986286/5cd5ebaf-4af8-4825-ab37-65281873d41c)
![Bildschirmfoto vom 2024-04-25 23-04-40](https://github.com/SharezoneApp/sharezone-app/assets/88986286/5731ec3b-4ff0-4b38-81ba-75b546a08257)
![Bildschirmfoto vom 2024-04-25 23-09-40](https://github.com/SharezoneApp/sharezone-app/assets/88986286/cc55a320-4652-4eff-8f03-3359699cf893)

## Tested device

- OS: Linux
- Browser: Chromium Version 123.0.6312.122 (snap build; 64bit)
- UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
- App type: WebApp

- App version: 2.0.1(0) and 2.0.2-alpha(0)

**Comment by nilsreichardt** [comment]
Hi @deep2web 👋

Thanks for your bug report! I immediately looked into this issue and fixed it.
