### ISSUE TITLE
Different storage limits in Sharezone Plus overview

### ISSUE THREAD

**Issue by ImGxrke** [SharezoneApp/sharezone-app#1565]
## Describe the bug

In the SZ+ overview there are mentioned two different limits. In the feature list there is a 30 GB limit however in the FAQ its 50 GB.

## Screenshots, videos or logs

![image](https://github.com/SharezoneApp/sharezone-app/assets/29801805/fd1b6c5c-4d88-4b73-80f9-e3264de4cbe2)
![image](https://github.com/SharezoneApp/sharezone-app/assets/29801805/256a24fe-8554-4947-800d-0b400c86687a)

## Tested device
- App version: 
2.0.2 (0)

**Comment by nilsreichardt** [comment]
Hi @ImGxrke, thanks for your report! I fixed the issue with #1566. Update will be available in the next days.
