### ISSUE TITLE
`Could not save term: Bad state: No element`

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#1568]
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Could not save term: Bad state: No element
       at ListBase.singleWhere(dart:collection)
       at L.singleWhere(ilist.dart:1899)
       at IList.singleWhere(ilist.dart:906)
       at GradesService._term(grades_service.dart:229)
       at GradesService.changeGradeTypeWeightForTerm(grades_service.dart:328)
       at CreateTermPageController.save(create_term_page_controller.dart:76)
```

https://console.firebase.google.com/u/0/project/sharezone-c2bd8/crashlytics/app/android:de.codingbrain.sharezone/issues/70b99289ed0259892c4b1ed3ac6e0e45

I think it happens when creating a term and immediately changing the grade type weight, but the term isn't returned from the reading stream. Therefore, it's not part of the `GradeService`:

https://github.com/SharezoneApp/sharezone-app/blob/99c7e293a6984d703effa7aedbacbfcb48d44066/app/lib/grades/pages/create_term_page/create_term_page_controller.dart#L75-L76

**Comment by nilsreichardt** [comment]
@Jonas-Sander Any ideas how to fix this (in case this happens what I think)?

**Comment by Jonas-Sander** [comment]
Maybe we could use a `bool _hasTopLevelCreatedOn` that is set here
https://github.com/SharezoneApp/sharezone-app/blob/d217d9a9b9f534c1432922449ad449e88759e0fd/app/lib/grades/grades_service/src/grades_repository.dart#L74-L88

and in `updateState` we add the top-level createdOn if that bool is false (and thus create a doc if not already existing)
