### ISSUE TITLE
"Herbstferien" are shown 2 times in the Ferien-Countdown

### ISSUE THREAD

**Issue by EvilMonkey09** [SharezoneApp/sharezone-app#1733]
The Herbstferien are shown twice in the Ferien-Countdown.

![image](https://github.com/user-attachments/assets/6c064752-558f-4eee-be11-722167b4902e)

**Comment by nilsreichardt** [comment]
Which state (Bundesland) is this?

**Comment by EvilMonkey09** [comment]
Niedersachen

**Comment by nilsreichardt** [comment]
This is the 1st of November, schulferien.org counts it as Herbstferien - to keep it simple, it would also leave it like this

![image](https://github.com/user-attachments/assets/844a7ebc-45a5-4380-b261-62d9b2d5d810)
