### ISSUE TITLE
Set up Alpha track for Android

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#215]
## Description
We already have an alpha version for the web app: https://alpha.web.sharezone.net. We can set up exactly the same thing for Android with Firebase Distribution.

Similar to the alpha web app, we would **not** increase the build version or the app build code for every build because this would require a big overhead.

For every new release are the users notified that there is a new version available.

## Advantages
We can advertise this Alpha version to bring some users to this track. These users would use our app and might catch some bugs. This is helpful because we need a lot of time until we have a 100% test coverage (also with a lot of integration tests) to be really sure we have no bugs in our app.

**Comment by nilsreichardt** [comment]
@Jonas-Sander What do you think about this? I think it will help us a bit and is easy to set up.

**Comment by Jonas-Sander** [comment]
Yeah sure, we can try it out 👍
