### ISSUE TITLE
Instagram to Jonas profile is incorrect

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#238]
## Description
https://github.com/SharezoneApp/sharezone-app/blob/cd0d7c8ba2d29644f5cd8a1562311c2edebfbb82/app/lib/pages/settings/src/subpages/about/widgets/team.dart#L67

@Jonas-Sander Your Instagram name is outdated in the about us page. Should I update the name or just remove the Instagram button for you?

**Comment by Jonas-Sander** [comment]
Remove it please:)

Thanks 🙏💙
