### ISSUE TITLE
Request push notification permission for Android 13

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#262]
Android 13 requires apps to request permission to send push notifications, similar as iOS does it. Therefore, we need to adjust the `requestIOSPermissions` method and add the ask for push notifications permissions screen into the onboarding for Android 13 devices.

https://github.com/SharezoneApp/sharezone-app/blob/769a8bdbe31178e646b4ad9dc4fc38db59c00884/app/lib/notifications/firebase_messaging_callback_configurator.dart#L128

**Comment by nilsreichardt** [comment]
We need to update Firebase: https://github.com/firebase/flutterfire/pull/9348

**Comment by Jonas-Sander** [comment]
@nilsreichardt We're still not on an up-to-date version where we can request the permissions, are we?

**Comment by nilsreichardt** [comment]
> We're still not on an up-to-date version where we can request the permissions, are we?

Yeah, correct. Updating to the newest Firebase is not that straightforward. However, it's already on my roadmap because it's required for flavors on macOS and web
