### ISSUE TITLE
Pubspec.yaml not in version control

### ISSUE THREAD

**Issue by PascalGehring** [SharezoneApp/sharezone-app#272]
I just cloned the project and realised that there is no pubspec.yaml file present. Maybe it's not in the version control...

**Comment by PascalGehring** [comment]
nvm, I realised that there is one present in the app folder :)

**Comment by nilsreichardt** [comment]
@PascalGehring I recommend also reading our [CONTRIBUTING.md](https://github.com/SharezoneApp/sharezone-app/blob/main/CONTRIBUTING.md). This should help to set up everything. If something is unclear in the CONTRIBUTING.md, let me know :)

**Comment by PascalGehring** [comment]
Thanks :)
