### ISSUE TITLE
Holiday countdown is displaying the name of the holidays differently

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#305]
## Description

The word "nordrhein-westfalen" should not be in the holiday countdown box 🤔 It's the same for other states.

### Android

![telegram-cloud-photo-size-2-5307994114140260077-y](https://user-images.githubusercontent.com/24459435/192905413-dba079e4-2602-4443-9ae8-21c48e225d98.jpg)

### Web

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24459435/192905463-f189dc23-b32b-4d8e-83ff-2d00215adb0a.png">

**Comment by nilsreichardt** [comment]
@Jonas-Sander This is coming from the holiday API, right?

**Comment by Jonas-Sander** [comment]
Yeah, we proxy it in a CF, but don't change the response content whatsoever.

**Comment by nilsreichardt** [comment]
Ah, we're already using a CF as proxy? Because is open branch for this: [remove-http-holiday-api-client](https://github.com/SharezoneApp/sharezone-app/tree/remove-http-holiday-api-client)

**Comment by Jonas-Sander** [comment]
From what I know we do, although I don't know if we had published the change to all platforms.

**Comment by nilsreichardt** [comment]
I have also created in issue in the repository of the API: https://github.com/paulbrejla/ferien-api/issues/19
