### ISSUE TITLE
Feature discovery for selecting a school class in the timetable is buggy

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#309]
![image](https://user-images.githubusercontent.com/24459435/192994197-822b85b6-c948-41ab-95dc-a5d75897980f.png)

**Comment by nilsreichardt** [comment]
@Jonas-Sander I think it's the best option to just remove the feature discovery because this feature isn't new anymore.

**Comment by Jonas-Sander** [comment]
Yeah, sounds good
