### ISSUE TITLE
Add `sharezone_lints` package

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#316]
I would like to add our own internal lints package (this package is not published), which should be used to by our packages in `lib`. This way we can ensure the same code quality in the whole repository. The `sharezone_lints` package should just extend the `flutter_lints`.

**Comment by nilsreichardt** [comment]
@Jonas-Sander What you are thoughts on a `sharezone_lints`? If it sounds good, I would add it 👍

**Comment by Jonas-Sander** [comment]
Sounds good to me 👍
