### ISSUE TITLE
Use the `sharezone_lints` for all packages.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#37]
E.g. the `lint` package.

**Comment by Jonas-Sander** [comment]
> It should be fixed with #37

Should be fixed with what? #37 is this issue.
Also some packages had different analysis_options from what I remember so we would have to fix some lints to achieve this I think

**Comment by nilsreichardt** [comment]
Oh, I wanted to use #316. However, we can still keep this issue open and maybe change the title to use something like "Use `sharezone_lints` in all package"
