### ISSUE TITLE
Uploading a file on web doesn't work anymore

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#374]
## Describe the bug

Since #369 has deleted the `web_firebase_file_uploader.dart` file, it's not possible to upload files on web anymore. When #221 is implemented, we can reimplement `web_firebase_file_uploader.dart`.

**Comment by Jonas-Sander** [comment]
We shouldn't need to reimplmement `web_firebase_file_uploader.dart` since https://pub.dev/packages/firebase_storage works on web now. Maybe I forgot to delete some conditional import somewhere? I haven't looked at it further.

**Comment by nilsreichardt** [comment]
The `mobile_firebase_file_uploader.dart` uses the `putFile()` methods of `FirebaseStorage`, but for web we need to use the `putData` method. Either we add a `web_firebase_file_uploader.dart` where we use the `putData()` method or we change the `mobile_firebase_file_uploader.dart` so that it can detect if it should use `putData()` or `putFile()`. Maybe the second option is better because otherwise we would need to a lot of business logic.

**Comment by Jonas-Sander** [comment]
ahhh omg I totally forgot about this problem 🙄🙄

Shouldn't the second be not possible because we can't import `dart:io` on web? I mean thats why we had to use two classes anyways and choose the correct implementation via conditional imports.

**Comment by nilsreichardt** [comment]
> Shouldn't the second be not possible because we can't import dart:io on web? I mean thats why we had to use two classes anyways and choose the correct implementation via conditional imports.

No, the second case is still possible because we have the abstraction with `LocalFile`. The reason for the files was that there was no Firebase web support via the official package and we need to use the `firebase` package.
