### ISSUE TITLE
Fix `sz deploy web-app` command.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#375]
Since #369 using the deploy command for the web app is broken since the Google credentials are not imported via the `index.html` anymore, but via Dart code. This means that all web apps uploaded via this method will be using the debug/dev project.

**Comment by Jonas-Sander** [comment]
I haven't actually tested it out yet, but I'm pretty sure its broken.
Related: #374

**Comment by nilsreichardt** [comment]
Already working on it :)
