### ISSUE TITLE
Only build app previews when the pull request has a specific label

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#381]
At the moment, we are building for every app pull request the app previews. However, there are a lot of pull requests (like #380) where building the app previews is not needed which uses our Codemagic budget.

An idea would be to only build the app previews when the pull request has a specific label, like `build-app-preview`.

**Comment by nilsreichardt** [comment]
@Jonas-Sander Should also build the web preview only when the PR has the `build-app-preview` label? Building the web preview is free for us so the money is not the problem. I was thinking about this because it's a bit annoying to get always the GitHub push notification that some commented. What do you think?

**Comment by Jonas-Sander** [comment]
> @Jonas-Sander Should also build the web preview only when the PR has the `build-app-preview` label? Building the web preview is free for us so the money is not the problem. I was thinking about this because it's a bit annoying to get always the GitHub push notification that some commented. What do you think?

I actually like that it's build automatically without any label but I'm also annoyed at the notification. Is there some way that we're not notified?

**Comment by nilsreichardt** [comment]
Seems so that this is not possible :/ I only find this [question](https://webapps.stackexchange.com/questions/119494/disable-notifications-from-github-bots) but it does not work with github-actions bot. GitHub says that this is not user.

**Comment by Jonas-Sander** [comment]
So what do you think? Only build the web preview with the label as well?

**Comment by nilsreichardt** [comment]
Even when the notifications are a bit annoying I think to always build the web preview the better option. The reason for this is that often it's enough to see the web preview to test feature and therefore we save more build minutes because we would use the android / ios preview only if really need it

**Comment by Jonas-Sander** [comment]
ye i agree
