### ISSUE TITLE
The border of text fields it's not good visible in dark mode

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#384]
| How it should be (current version from PlayStore) | How it currently is (current `main`) |
|-|-|
| ![telegram-cloud-photo-size-2-5463272927240768560-y](https://user-images.githubusercontent.com/24459435/221359322-8ae2981b-5c51-4abb-ba7b-6f3593db18d0.jpg) | ![telegram-cloud-photo-size-2-5463272927240768559-y](https://user-images.githubusercontent.com/24459435/221359328-9fc3cd1d-69b3-499d-9cd1-d0fc541cd461.jpg) |

**Comment by Yashdon999** [comment]
Hey, I would like to work on this issue

**Comment by nilsreichardt** [comment]
Hey @Yashdon999, cool you do this and open a pull request :) I think the issue has been introduced in #51, so it's something releated to the Theme changes. Let's me know, if you have any questions. You can also ask your questions in our Discord server: https://sharezone.net/discord

**Comment by Chaitu-Tatipamula** [comment]
can i go work on this

**Comment by Yashdon999** [comment]
I will not be able to work on this because I do not understand the code

**Comment by UtkarshDeoli** [comment]
Hey Can i work on it @nilsreichardt ?
