### ISSUE TITLE
Write an GitHub Action that keeps the paths for `merge_queue`, `pull_request` and fallback CIs in sync

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#454]
In our GitHub Actions we have several paths filter. Unfortunately, we need to manually sync these filters with two locations:
* (maybe) Fallback CIs
* (maybe) Merge Queues

It's easy to forget to keep these in sync. Therefore, an GitHub Action check which would check this, would be very helpful.

**Comment by Jonas-Sander** [comment]
Fixed via #456 and #457
