### ISSUE TITLE
Replace `package:tuneup` used in the Sharezone CLI.

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#480]
Since `package:tuneup` [has been discontinued](https://github.com/google/tuneup.dart/issues/96) we should replace it.  
We can use `flutter analyze` and `dart analyze` instead, but neither have `--fail-on-todos` flag which we use.  
We might have to implement a seperate "fail on TODOs" step ourselves.

See also [this comment](https://github.com/SharezoneApp/sharezone-app/pull/478#issuecomment-1464468646) on #478

**Comment by nilsreichardt** [comment]
What if we make `TODO`s to warnings in our `analysis_options.yaml`?:

```yaml
analyzer:
  errors:
    todo: warning
```

Having TODOs and running `dart analyze` returns exit code 2.

**Comment by Jonas-Sander** [comment]
Daaammmnnn you smaart
