### ISSUE TITLE
Apple Sign In will not work with iOS 15

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#49]
## Description
The problem is that we are using a version of `sign_in_with_apple`, which is does not support iOS 15 (see more details in https://github.com/aboutyou/dart_packages/issues/213).

To fix this, we need to upgrade `sign_in_with_apple` to `^3.1.0` or higher.

**Comment by Jonas-Sander** [comment]
@nilsreichardt We have `sign_in_with_apple: ^3.3.0`. So I guess this can be closed? Do you know if this is still a problem?

**Comment by nilsreichardt** [comment]
Yes, we can close it 👍
