### ISSUE TITLE
Icons looking weird on alpha web app 

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#57]
## Describe the bug
The Material Icons are looking weird / wrong on alpha web app.

## Steps to Reproduce
1. Go to https://alpha.web.sharezone.net
2. Login
3. Click trough app

## Current _broken_ behavior
![image](https://user-images.githubusercontent.com/24459435/143125617-4ea4d18c-159f-4f94-9e7b-6fc6c2f44bcd.png)
![image](https://user-images.githubusercontent.com/24459435/143125897-84621917-74fc-47ba-9285-59295d4845f6.png)
![image](https://user-images.githubusercontent.com/24459435/143126211-19cf095d-4192-486a-ad4a-6c88637c6228.png)
![image](https://user-images.githubusercontent.com/24459435/143127196-43a4a8f8-45cb-41fc-8029-e2c63f6ba399.png)

## Expected behavior
See Android / iOS app (I'm now too lazy to make the screenshots in the android / ios app 😅)

## Screenshots, videos or logs
See broken behavior

## Tested device
 - Device: MacBook Pro M1
 - Browser: Chrome `95.0.4638.69`
 - OS: macOS 12.0.1
 - App version: 1.6.1 (Alpha Web-App)

**Comment by Jonas-Sander** [comment]
I think this is not an issue anymore so I'm gonna close this issue
