### ISSUE TITLE
Options "Sortiere nach Fach" and "Sortiere nach Datum" are swapped

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#826]
![IMG_8A0971CBB098-1](https://github.com/SharezoneApp/sharezone-app/assets/24459435/5e3d24b9-4b06-4a77-a3dd-58b561174fc9)

It displays "Sortiere nach Fach" but the homeworks are already a sorted by the subject. Using here "Sortiere nach Datum" would make more sense

**Comment by nilsreichardt** [comment]
@Jonas-Sander What do you think?

**Comment by Jonas-Sander** [comment]
Would be okay for me to swap the text. I think my idea back then was that it should be displayed like this to convey "current active sort: subject".  

Maybe it also wasn't completely clear how the UI should behave. I could imagine that there might have been the option that this isn't a button but more of a drop-down menu in which case the current behavior would be better in my opinion.

**Comment by nilsreichardt** [comment]
> I think my idea back then was that it should be displayed like this to convey "current active sort: subject".

This would also okay for me to keep the behavior but then change the text to "Sortiert nach Fach" instead of "Sortiere nach Fach"

**Comment by Jonas-Sander** [comment]
Ah yes, good idea!

**Comment by nilsreichardt** [comment]
Fixed with #832
