### ISSUE TITLE
Add feature flag to disable buying Sharezone Plus

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#932]
## Description

It would be good to have the option to disable the purchase of Sharezone Plus for some possible future reasons. Reasons could be:

* We shut down Sharezone Plus
* Our servers are currently down
* We have a major payment problem

Not sure if we should implement this with Remote Config. Maybe a cloud function when clicking the subscribe button would be a better solution because it's immediately available.

## Open questions

* Should we block the payment if the available check couldn't be made (fail open vs. fail closed)?
  * Pro: If the cloud functions are down, the chances that Firebase is down is high. Therefore, buying Sharezone Plus would not be possible, which would be good.
  * Con: If for some unimportant the cloud function fails (but the cloud functions are healthy), a potential subscription could be missed.
  * I think we should fail closed and block the payment. However, we should use the `retry` method.

## Possible design of the cloud function:

Input:
* Platform: Android | iOS | Web | macOS (allows us to block the payment for a specific platform).
* App version: v1.3.7 (allows us to block payment for a specific version)

Answer:
* Status: Sharezone is available | Sharezone is _not_ available
* Error message (optional): e.g. "Buying Sharezone Plus is temporarily disabled. Please come back in a few hours", "We have stopped offering Sharezone Plus".

_Note: I think we should keep this system simple and not over-engineer it (it has a lot of potential to be over-engineered) because disabling the purchase of Sharezone Plus should not happen that often._

**Comment by nilsreichardt** [comment]
@Jonas-Sander FYI

**Comment by Jonas-Sander** [comment]
Can't people also make in app purchases from outside the app (at least on iOS)?

**Comment by nilsreichardt** [comment]
Yes, this is in a limited way possible. I couldn't find an option to make a new subscribe a subscription. However, I could resubscribe to an expired subscription in the App Store.

And yes, we need to know that it would still be possible to make purchases from out of the app. But I would guess that +99% of the people are buying the subscription insides the app.
